### ISSUE TITLE
add support to refer on locally configured bootstrap

### ISSUE THREAD

**Issue by veenone** [web-innovate/bootstraped-multi-test-results-report#87] opened 2017-12-29 04:20 UTC
Please add support on the api to use locally installed bootstrap / datatables / jquery .
This will be helpful if the jenkins server is not connected to the internet at all (as in my case)

**Comment by BogdanLivadariu** [comment] 2018-07-26 07:45
duplicate of #6

**Closed by BogdanLivadariu** 2018-07-26 07:45 UTC
